<?php
/**
 * Http.php
 * Created by PhpStorm.
 * User: ameng
 * Date: 2017/4/17
 */
namespace app\common\controller;

use app\common\component\ApiClient;
use app\common\model\TraceHttpLog;
use think\Config;
use think\Controller;
use think\Request;
use think\Response;
use think\Session;
use wechat\TPWechat;

class Base extends Controller
{
    public $page_title = ''; // 页面标题
    public $assign     = [];
    protected $_open_id   = '';
    public $user_id = 0;

    public function __construct(Request $request)
    {
        // 记录来访者信息
        //TraceHttpLog::trace();

        // 仅限微信浏览器访问

        // session 初始化
        Session::init(Config::get('session'));

        // 获取openid
        $request        = Request::instance();
        $this->_open_id = Session::get('openid');
        $this->user_id  = Session::get('user_id');
        if (empty($this->_open_id)) {
            $request_open_id    = $request->get('openid');

            if (empty($request_open_id)) {
                $this->error('非法访问，请在订阅号输入m，从网站入口进入。');
            }
            // 未登陆
            if (strtolower($request->module()) != 'index' || strtolower($request->controller()) != 'site' || strtolower($request->action()) != 'login') {
                $this->redirect('/index/site/login?openid='.$request_open_id);
            } else { // 登录后再进登录页面则会自动跳到首页
                if(isset($session['openid']) && !empty($session['openid'])) {
                    $this->redirect('/index/home/index');
                }
            }
        }

       // $this->_open_id = $this->_getOpenId();

        parent::__construct($request);
    }


    // 自定义模板渲染
    public function fetch($template = '', $vars = [], $replace = [], $config = [])
    {
        $vars   = empty($vars)?$this->assign:$vars;
        $vars['page_title'] = $this->page_title;
        return parent::fetch($template, $vars, $replace, $config); // TODO: Change the autogenerated stub
    }

    private function _getOpenId ()
    {
        $data['grant_type'] = 'client_credential';
        $data['appid']      = Config::get('wx_options.appid');
        $data['secret']     = Config::get('wx_options.appsecret');
        $api_client         = new ApiClient();
        $ret                = $api_client->doRequest('https://api.weixin.qq.com/cgi-bin/token', $data);
        if (isset($ret['access_token'])) {
           // TODO
        }
    }

    /**
     * 返回AJAX
     * @param $data
     * @param int $code
     * @param string $msg
     * @return string
     */
    public function ajaxReturn ($code=0, $msg = '', $data='')
    {
        $body   = [
            'err_code'  => $code,
            'err_msg'   => $msg,
            'data'      => $this->_filter_null($data)
        ];

        echo json_encode($body, JSON_UNESCAPED_UNICODE);
        if (function_exists('fastcgi_finish_request')) {
            // 提高页面响应
            fastcgi_finish_request();
        }
        exit;
    }

    /**
     * 过滤NULL值
     * @param $data
     * @return mixed
     */
    private function _filter_null ($data)
    {
        if (is_array($data)) {
            foreach($data as $key=>&$val) {
                if(is_array($val)) {
                    $val = $this->_filter_null($val);
                } else {
                    if($val === null){
                        $val    = '';
                    }
                }
            }
        } else {
            if ($data === null) {
                $data   = '';
            }
        }

        return $data;
    }

}